apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-orderer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: local-pv-orderer
