apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-org2-peer2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  volumeName: local-pv-org2-peer2
