apiVersion: batch/v1
kind: Job
metadata:
  name: create-certs
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: create-certs
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: mypvc
      containers:
        - name: create-certs
          image: hyperledger/fabric-ca-tools:latest
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "350m"
          volumeMounts:
            - mountPath: /data
              name: fabricfiles
              subPath: ca-orderer
            - mountPath: /scripts
              name: fabricfiles
              subPath: scripts
            - mountPath: /organizations
              name: fabricfiles
              subPath: organizations
            - mountPath: /ca-org1
              name: fabricfiles
              subPath: ca-org1
            - mountPath: /ca-org2
              name: fabricfiles
              subPath: ca-org2
          command:
            - /bin/sh
            - -c
            - |
              /scripts/orderer-certs.sh &&
              /scripts/org1-certs.sh 1 &&
              /scripts/org1-certs.sh 2 &&
              /scripts/org2-certs.sh 1 &&
              /scripts/org2-certs.sh 2
              
      restartPolicy: Never
