apiVersion: batch/v1
kind: Job
metadata:
  name: install-chaincode
spec:
  template:
    spec:
      containers:
      - name: install-chaincode
        image: hyperledger/fabric-tools:latest
        command: ["/bin/bash", "-c"]
        args: ["./scripts/install-chaincode.sh"]
        volumeMounts:
        - name: fabric
          mountPath: /scripts
          subPath: scripts
        - name: fabric
          mountPath: /organizations
          subPath: organizations
        - name: fabric
          mountPath: /configtx
          subPath: configtx
        - name: fabric
          mountPath: /chaincode
          subPath: chaincode

      restartPolicy: Never
      volumes:
      - name: fabric
        persistentVolumeClaim:
          claimName: mypvc


