apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ca-org1
spec:
  serviceName: "ca-org1"
  replicas: 1
  selector:
    matchLabels:
      app: ca-org1
  template:
    metadata:
      labels:
        app: ca-org1
    spec:
      containers:
      - name: ca-org1
        image: hyperledger/fabric-ca:latest
        volumeMounts:
        - name: ca-org1-data
          mountPath: /etc/hyperledger/fabric-ca-server
          subPath: ca-org1
        ports:
        - containerPort: 7054
        command: ["fabric-ca-server", "start", "-b", "admin:adminpw", "--port", "7054", "-d"]
        env:
        - name: FABRIC_CA_SERVER_CA_NAME
          value: ca-org1
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "true"
        - name: FABRIC_CA_SERVER_CSR_HOSTS
          value: "ca-org1"
      volumes:
      - name: ca-org1-data
        persistentVolumeClaim:
          claimName: mypvc
