apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orderer
spec:
  selector:
    matchLabels:
      app: orderer
  serviceName: "orderer"
  replicas: 1
  template:
    metadata:
      labels:
        app: orderer
    spec:
      nodeName: blockchain-precision-3660
      containers:
        - name: orderer
          image: hyperledger/fabric-orderer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CONFIGTX_ORDERER_ADDRESSES
              value: "orderer:7050"
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_LISTENPORT
              value: "7050"
            - name: ORDERER_GENERAL_LOGLEVEL
              value: debug
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp
            - name: ORDERER_GENERAL_LOCALMSPID
              value: OrdererMSP
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: file
            - name: ORDERER_GENERAL_GENESISFILE
              value: /system-genesis-block/genesis.block
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: /organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: /organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: /organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt
            - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
              value: /organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key
            - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
              value: /organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
          resources:
            limits:
              memory: "250Mi"
              cpu: "250m"
            requests:
              memory: "200Mi"
              cpu: "150m"
          volumeMounts:
            - name: mypvc
              mountPath: /organizations
              subPath: organizations
            - name: mypvc
              mountPath: /system-genesis-block
              subPath: channel-artifacts
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: mypvc
