apiVersion: v1
kind: Service
metadata:
  name: orderer
  labels:
    app: hyperledger
    component: orderer
spec:
  selector:
    app: orderer
  ports:
    - protocol: TCP
      port: 7050
      targetPort: 7050
  type: ClusterIP
