---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchdb-org1-peer1
spec:
  serviceName: "couchdb-org1-peer1-service"
  replicas: 1
  selector:
    matchLabels:
      app: couchdb-org1-peer1
  template:
    metadata:
      labels:
        app: couchdb-org1-peer1
    spec:
      nodeName: blockchain-precision-3660
      containers:
        - name: couchdb
          image: hyperledger/fabric-couchdb:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5984
          env:
            - name: COUCHDB_USER
              value: "admin"
            - name: COUCHDB_PASSWORD
              value: "adminpw"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: mypvc
              mountPath: /var/lib/couchdb
              subPath: couchdb-data-org1-peer1
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: local-pvc-org1-peer1

---
apiVersion: v1
kind: Service
metadata:
  name: couchdb-org1-peer1-service
spec:
  type: NodePort
  selector:
    app: couchdb-org1-peer1
  ports:
    - protocol: TCP
      port: 5984
      targetPort: 5984
      nodePort: 30000  # Choose a port in the range 30000-32767 or let Kubernetes assign one

