apiVersion: v1
kind: Service
metadata:
  name: peer1-org1-example-com
spec:
  selector:
    app: org1-peer1  # This should match the labels in the StatefulSet
  ports:
    - name: peer
      protocol: TCP
      port: 7051
      targetPort: 7051
    - name: chaincode
      protocol: TCP
      port: 7052
      targetPort: 7052

