apiVersion: v1
kind: Service
metadata:
  name: peer2-org1-example-com
spec:
  selector:
    app: org1-peer2  # Ensure this matches the labels in the StatefulSet
  ports:
    - name: peer
      protocol: TCP
      port: 7051
      targetPort: 7051
    - name: chaincode
      protocol: TCP
      port: 7052
      targetPort: 7052

