apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: org2-peer2
spec:
  serviceName: "peer2-org2-example-com"  # Ensure this matches the Service name
  replicas: 1
  selector:
    matchLabels:
      app: org2-peer2
  template:
    metadata:
      labels:
        app: org2-peer2  # Ensure this matches the selector in the Service
    spec:
      nodeName: blockchain-precision-3660
      containers:
        - name: org2-peer2
          image: hyperledger/fabric-peer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CORE_PEER_ID
              value: "org2-peer2"
            - name: CORE_PEER_ADDRESS
              value: "peer2-org2-example-com:7051"  # Include port number
            - name: CORE_PEER_LISTENADDRESS
              value: "0.0.0.0:7051"
            - name: CORE_PEER_CHAINCODEADDRESS
              value: "chaincode-service:7052"
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: "peer2-org2-example-com:7051"  # Include port number
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: "peer2-org2-example-com:7051"  # Include port number
            - name: CORE_PEER_LOCALMSPID
              value: "Org2MSP"
            - name: FABRIC_LOGGING_SPEC
              value: "INFO"
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: "/organizations/peerOrganizations/org2.example.com/peers/peer2.org2.example.com/tls/server.crt"
            - name: CORE_PEER_TLS_KEY_FILE
              value: "/organizations/peerOrganizations/org2.example.com/peers/peer2.org2.example.com/tls/server.key"
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: "/organizations/peerOrganizations/org2.example.com/peers/peer2.org2.example.com/tls/ca.crt"
            - name: CORE_PEER_MSPCONFIGPATH
              value: "/organizations/peerOrganizations/org2.example.com/peers/peer2.org2.example.com/msp"
            - name: COUCHDB_ADDRESS
              value: "couchdb-org1-peer1-service:5984"
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: "CouchDB"
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
              value: "couchdb-org1-peer1-service:5984"
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
            requests:
              memory: "1.5Gi"
              cpu: "300m"
          volumeMounts:
            - name: mypvc
              mountPath: /organizations
              subPath: organizations
            - name: peer
              mountPath: /var/hyperledger/production
              subPath: production-peer1
            - name: mypvc
              mountPath: /chaincode
              subPath: chaincode
            - name: mypvc
              mountPath: /builder
              subPath: builder
            - name: mypvc
              mountPath: /etc/hyperledger/fabric/core.yaml
              subPath: configtx/core.yaml
            - name: mypvc
              mountPath: /configtx
              subPath: configtx
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: mypvc
        - name: peer
          persistentVolumeClaim:
            claimName: local-pvc-org2-peer2

